### TEST INIT GET
GET http://127.0.0.1:8083/ HTTP/1.1

### ADD SCHEDULE

curl -X POST http://localhost:8083/api/v1/schedule/2 \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImVuZGVyYnJvLm1haW5AeWFuZGV4LnJ1IiwiU2Vzc2lvbklkIjoiNTQ1NDIzYTItNmVlZS00ODFjLWEwYjMtZjBhNGRjNGRhOWQxIiwiZXhwIjoxNzMwNTY3OTc4fQ.NflnuYwyaycDg0ZFV4SlcXCIbwORyuUy8WO0WlXmQss"


### SEND CODE FOR AUTH

curl -X POST http://localhost:8083/api/v1/email/send \
-H "Content-Type: application/json" \
-d '{
    "email": "enderbro.main@yandex.ru"
}'

## EXAMPLE OF ANSWER
# {
#   "id": "7470fe1c-2d41-4549-b34d-d1201397488b",
#   "email": "enderbro.main@yandex.ru"
# }

880596

### SEND CODE FOR CONFIRM

curl -X POST http://localhost:8083/api/v1/email/7470fe1c-2d41-4549-b34d-d1201397488b/confirm
-H "Content-Type: application/json" \
-d '{
    "code": 880596
}'

## EXAMPLE OF ANSWER
# {
#   "id": "545423a2-6eee-481c-a0b3-f0a4dc4da9d1",
#   "created_at": "2024-11-02T17:19:38.4816974+05:00",
#   "updated_at": "2024-11-02T17:19:38.4816974+05:00",
#   "deleted_at": null,
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImVuZGVyYnJvLm1haW5AeWFuZGV4LnJ1IiwiU2Vzc2lvbklkIjoiNTQ1NDIzYTItNmVlZS00ODFjLWEwYjMtZjBhNGRjNGRhOWQxIiwiZXhwIjoxNzMwNTY3OTc4fQ.NflnuYwyaycDg0ZFV4SlcXCIbwORyuUy8WO0WlXmQss",
#   "email": "enderbro.main@yandex.ru"
# }

### GET SESSION

curl -X GET http://localhost:8083/api/v1/session -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImVuZGVyYnJvLm1haW5AeWFuZGV4LnJ1IiwiU2Vzc2lvbklkIjoiYjY0YjQxNDItZjMxYy00ODM4LWJhN2UtMDM2ZTE0Nzk3YTA0IiwiZXhwIjoxNzI1MjkxMDk1fQ.KhP-7_gtHHh3KdxTrMXPxRGJluo-JmZ_7wij5lLEfts"


### UPLOAD VIDEO






